Repository HunterJuneau/dine-and-dash, pull requests merged in 2021-11, with the labels that each got.

#81 User profile
  API/DineNDash/DineNDash/DataAccess/UserRepository.cs
  API/DineNDash/DineNDash/Startup.cs
  Front End/src/App/index.js
  Front End/src/components/NavBar.js
  Front End/src/components/products/Productcard.js
  Front End/src/components/users/UserCard.js
  Front End/src/helpers/Routes.js
  Front End/src/helpers/data/UserData.js
  Front End/src/views/AllUsersView.js
  Front End/src/views/UserProfileView.js
Labels: enhancement

#82 Bj user orders v2
  API/DineNDash/DineNDash/Controllers/OrderController.cs
  API/DineNDash/DineNDash/DataAccess/OrderRepository.cs
  Front End/src/App/index.js
  Front End/src/components/users/UserCard.js
  Front End/src/helpers/Routes.js
  Front End/src/helpers/data/UserData.js
  Front End/src/views/AllUsersView.js
  Front End/src/views/UserOrdersView.js
  Front End/src/views/UserProfileView.js
Labels: enhancement

#84 Product View Back Update
  Front End/src/components/products/Productcard.js
  Front End/src/helpers/Routes.js
  Front End/src/views/InventoryView.js
  Front End/src/views/SingleProduct.js
Labels: enhancement

#87 Change to Add ProductOrders API Call and created API Call to Get All ProductOrders by Order Id
  API/DineNDash/DineNDash/Controllers/OrderController.cs
  API/DineNDash/DineNDash/Controllers/ProductOrderController.cs
  API/DineNDash/DineNDash/DataAccess/OrderRepository.cs
  API/DineNDash/DineNDash/DataAccess/ProductOrderRepository.cs
  API/DineNDash/DineNDash/Models/CreateProductOrderCommand.cs
  API/DineNDash/DineNDash/Models/DetailedOrderView.cs
  API/DineNDash/DineNDash/Models/ProductOrder.cs
  API/DineNDash/DineNDash/Startup.cs
  Front End/src/helpers/Routes.js
  Front End/src/views/UserOrdersView.js
  Front End/src/views/UserSingleOrderDetailsView.js
Labels: enhancement

#91 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  ISSUE_TEMPLATE.md
Labels: documentation

#92 Added private routes and admin only views
  Front End/sample.env
  Front End/src/App/index.js
  Front End/src/components/NavBar.js
  Front End/src/helpers/PrivateRoute.js
  Front End/src/helpers/Routes.js
  Front End/src/helpers/apiKeys.js
  Front End/src/helpers/data/OrderData.js
Labels: enhancement

#93 Bug fix for error when refreshing
  Front End/src/helpers/PrivateRoute.js
Labels: bug

#94 User's Order Details View and User's Payments View
  Front End/src/helpers/Routes.js
  Front End/src/helpers/data/PaymentData.js
  Front End/src/views/UserOrdersView.js
  Front End/src/views/UserPaymentsView.js
  Front End/src/views/UserProfileView.js
Labels: enhancement

#95 Get user by Firebase UID
  API/DineNDash/DineNDash/Controllers/UserController.cs
  API/DineNDash/DineNDash/DataAccess/UserRepository.cs
  API/DineNDash/DineNDash/Models/User.cs
  script.sql
Labels: enhancement

#98 Bj user cart
  API/DineNDash/DineNDash/Controllers/OrderController.cs
  API/DineNDash/DineNDash/Controllers/UserController.cs
  API/DineNDash/DineNDash/DataAccess/OrderRepository.cs
  API/DineNDash/DineNDash/DataAccess/PaymentRepository.cs
  API/DineNDash/DineNDash/DataAccess/ProductOrderRepository.cs
  API/DineNDash/DineNDash/Models/User.cs
  Front End/src/components/products/Productcard.js
  Front End/src/helpers/Routes.js
  Front End/src/helpers/auth.js
  Front End/src/helpers/data/OrderData.js
  Front End/src/helpers/data/UserData.js
  Front End/src/views/ProductViews/ProductsView.js
  Front End/src/views/UserOrdersView.js
Labels: enhancement, Purchasing

#99 Auth User Database Link
  API/DineNDash/DineNDash/Controllers/UserController.cs
  Front End/src/App/index.js
  Front End/src/components/NavBar.js
  Front End/src/helpers/Routes.js
  Front End/src/helpers/auth.js
  Front End/src/helpers/data/UserData.js
  Front End/src/views/UserProfileView.js
Labels: enhancement

#100 Profile View
  Front End/src/components/NavBar.js
  Front End/src/helpers/Routes.js
  Front End/src/views/UserOrdersView.js
  Front End/src/views/UserPaymentsView.js
  Front End/src/views/UserProfileView.js
Labels: enhancement

#103 User Cart
  API/DineNDash/DineNDash/Controllers/OrderController.cs
  API/DineNDash/DineNDash/DataAccess/OrderRepository.cs
  API/DineNDash/DineNDash/DataAccess/ProductOrderRepository.cs
  API/DineNDash/DineNDash/Models/DetailedOrderView.cs
  Front End/src/components/products/Productcard.js
  Front End/src/helpers/Routes.js
  Front End/src/helpers/data/OrderData.js
  Front End/src/views/ProductViews/ProductsView.js
  Front End/src/views/UserOrdersView.js
  Front End/src/views/UserPaymentsView.js
Labels: enhancement
